main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('plants/', views.plant_index, name='plant-index'),
  path('plants/<int:plant_id>/', views.plant_detail, name='plant-detail'),
  path('plants/create', views.PlantCreate.as_view(), name='plant-create'),
  path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plant-update'),
  path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plant-delete'),
  path('plants/<int:plant_id>/add-caring/', views.add_caring, name='add-caring'),
  path('plants/<int:plant_id>/add-photo/', views.add_photo, name='add-photo'),
  path('accounts/signup/', views.signup, name='signup'),
]

plantpartner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('main_app.urls')),
  path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

CARES = (
  ('W', 'Water'),
  ('F', 'Fertilizer'),
  ('M', 'Mist')
)

class Plant(models.Model):
  name = models.CharField(max_length=100)
  location = models.TextField(max_length=250)
  description = models.TextField(max_length=250)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name
  
  def get_absolute_url(self):
    return reverse("plant-detail", kwargs={"plant_id": self.id})
  
class Caring(models.Model):
  date = models.DateField()
  care = models.CharField(
    'Care Given',
    max_length=1,
    choices=CARES,
    default=CARES[0][0],
  )
  plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_care_display()} on {self.date}"
  
  class Meta:
    ordering = ['-date']

class Photo(models.Model):
  url = models.CharField(max_length=250)
  plant = models.OneToOneField(Plant, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for plant_id: {self.plant_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Caring

class CaringForm(ModelForm):
  class Meta:
    model = Caring
    fields = ['date', 'care']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Plant, Photo
from .forms import CaringForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'strammel-plant-partner'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('plant-index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

class Home(LoginView):
  template_name = 'home.html'

def about(request):
  return render(request, 'about.html')

@login_required
def plant_index(request):
  plants = Plant.objects.filter(user=request.user)
  return render(request, 'plants/index.html', { 'plants': plants, 'name': request.user.username })

@login_required
def plant_detail(request, plant_id):
  plant = Plant.objects.get(id=plant_id)
  caring_form = CaringForm()
  return render(request, 'plants/detail.html',  {'plant': plant, 'caring_form': caring_form })

@login_required
def add_caring(request, plant_id):
  form = CaringForm(request.POST)
  if form.is_valid():
    new_caring = form.save(commit=False)
    new_caring.plant_id = plant_id
    new_caring.save()
  return redirect('plant-detail', plant_id=plant_id)

class PlantCreate(LoginRequiredMixin, CreateView):
  model = Plant
  fields = ['name', 'location', 'description']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class PlantUpdate(LoginRequiredMixin, UpdateView):
  model = Plant
  fields = ['location', 'description']

class PlantDelete(LoginRequiredMixin, DeleteView):
  model = Plant
  success_url = '/plants/'

@login_required
def add_photo(request, plant_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex + photo_file.name[photo_file.name.rfind('.'):]
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      photo = Photo(url=url, plant_id=plant_id)
      plant_photo = Photo.objects.filter(plant_id=plant_id)
      if plant_photo.first():
        plant_photo.first().delete()
      photo.save()
    except Exception as err:
      print('An error occurred uploading file to S3: %s' % err)
  return redirect('plant-detail', plant_id=plant_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type='text/css' href="{% static 'css/about.css' %}">
{% endblock %}

{% block content %}
<section class="">
  <h1>The Forgetful Gardener's Best Friend</h1>
</section>
<hr />
<p class="page-content">
  Plant Partner is an app for people who struggle to keep plants alive. If you lack a green thumb, this is the app for you.
  <br/>
  <br/>
  Plant Partner makes it simple to know when you last completed basic houseplant care. Gone are the days of wondering if you watered the plants last week- or was it the week before? If you wish could keep plants in your home without neglecting them to death, use Plant Partner to keep you and your plants happy!
</p>
<div class="logo">
  <img src="{% static 'images/plant-partner-logo.png' %}" alt="The Plant Partner Logo">
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/favicon.png' %}"
  >
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans&family=Roboto:wght@300&display=swap" rel="stylesheet">
  <title>Plant Partner</title>
  <link rel="stylesheet" type='text/css' href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="/" class='home-link'>Plant Partner</a>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'plant-index' %}">My Plants</a></li>
          <li><a href="{% url 'plant-create' %}">Add a Plant</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type='text/css' href="{% static 'css/home.css'%}">
{% endblock %}

{% block content %}
<section class="logo-container">
  <div class="plant-container">
    <img src="{% static 'images/plant-partner-logo.png' %}" alt="The Plant Partner Logo">
  </div>
</section>
{% if not user.is_authenticated %}
<section>
  <form 
    action="{% url 'home' %}" 
    method="post" 
    class="login" 
    autocomplete="off"
  >
    <h2>Log In</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="btn submit">Log In</button>
  </form>
</section>
{% endif %}
{% endblock%}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type='text/css' href="{% static 'css/delete.css' %}">
{% endblock %}

{% block content %}
<div class="page-header">
  <img src="{% static 'images/gravestone.png' %}" alt="A gravestone icon">
  <h1>Delete Plant</h1>
  <img src="{% static 'images/gravestone.png' %}" alt="A gravestone icon">
</div>
<h2>Are you sure you want to delete the {{ plant.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'plant-detail' plant.id %}" class="btn secondary">
    Cancel
  </a>
  <p class="invisible"></p>
  <button type="submit" class="btn danger">Delete</button>
</form>
{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type='text/css' href="{% static 'css/form.css' %}">
{% endblock %}

{% block content %}
<div class="page-header">
  <img src="{% static 'images/orchid-left.png' %}" alt="An orchid icon pointing left">
  {% if plant %}
    <h1>Edit the {{ plant.name }}</h1>
  {% else %}
    <h1>Add a Plant</h1>
  {% endif %}
  <img src="{% static 'images/orchid.png' %}" alt="An orchid icon pointing right">
</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit</button>
</form>
{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link rel="stylesheet" type="text/css" href="{% static 'css/plants/plant-detail.css' %}">
<script defer src="{% static 'js/plant-detail.js' %}"></script>
{% endblock %}

{% block content %}
<section class="plant-container">
  <section class="plant">
    <h1>{{ plant.name }}</h1>
    <p id="file-name"></p>
    <div class="plant-img">
      {% if plant.photo.url %}
        <img 
          src="{{plant.photo.url}}" 
          alt="A photo of {{plant.name}}" 
          class="usr-img"
        >
      {% else %}
        <img 
          src="{% static 'images/default-plant.png' %}" 
          alt="A potted plant icon"
          class="default-img"
        >
      {% endif %}
    </div>
    <form 
      action="{% url 'add-photo' plant.id %}"
      enctype="multipart/form-data"
      method="POST"
    >
      {% csrf_token %}
      <label class="btn secondary">
        Choose photo
        <input type="file" name="photo-file" id="file-input">
      </label>
      <p class="invisible"></p>
      <button type="submit" class="btn submit">Upload Photo</button>
    </form>
    <div class="plant-details">
      <p>Located: {{ plant.location }}</p>
      <hr />
      <p>{{ plant.description }}</p>
    </div>
    <div class='plant-actions'>
      <a href="{% url 'plant-update' plant.id %}">
        <img src="{% static 'images/edit.png' %}" alt="A pencil on paper icon">
      </a>
      <a href="{% url 'plant-delete' plant.id %}">
        <img src="{% static 'images/bin.png' %}" alt="A garbage can icon">
      </a>
    </div>
  </section>
</section>
<div class="care-container">
  <section class="care">
    <div class="subsection-title">
      <img src="{% static 'images/spray.png' %}" alt="A spray bottle icon">
      <img src="{% static 'images/fertilizer.png' %}" alt="A fertilizer icon">
      <img src="{% static 'images/watering-can.png' %}" alt="A watering can icon">
    </div>
    <h3>Tend to {{ plant.name }}</h3>
    <form 
      action="{% url 'add-caring' plant.id %}" 
      method="post" 
      class="subsection-content" 
      autocomplete="off"
    >
      {% csrf_token %}
      {{ caring_form.as_p }}
      <button type="submit" class="btn submit">Add</button>
    </form>
    <h3>Past Care</h3>
    {% if plant.caring_set.all.count %}
    <div class="table">
      <table>
        <thead>
          <tr><th>Date</th><th>Care Given</th></tr>
        </thead>
        <tbody>
          {% for caring in plant.caring_set.all %}
            <tr>
              <td>{{caring.date}}</td>
              <td>{{caring.get_care_display}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% else %}
      <div class="subsection-content">
        <p>{{plant.name}} has no recorded care.</p>
      </div>
    {% endif %}
  </section>
</div>
{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type='text/css' href="{% static 'css/plants/plant-index.css'%}">
{% endblock %}

{% block content %}
<section class="page-header">
  <h1>{{ name }}'s Plants</h1>
</section>

<section class="card-container">
  {% if plants.count %}
    {% for plant in plants %}
      <div class="card">
        <a href="{% url 'plant-detail' plant.id %}">
          <div class="card-content">
            <div class="card-img-container">
              {% if plant.photo.url %}
                <img src="{{plant.photo.url}}" alt="A photo of {{plant.name}}" class="usr-img">
              {% else %}
                <img src="{% static 'images/default-plant.png' %}" alt="A potted plant icon">
              {% endif %}
            </div>
            <h2 class="card-title">{{ plant.name }}</h2>
            <p>{{ plant.location }}</p>
          </div>
        </a>
      </div>
    {% endfor %}
  {% else %}
    <h2 class="no-plants">No plants to display</h2>
  {% endif %}
</section>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <img src="{% static 'images/wheelbarrow-left.png' %}" alt="A wheelbarrow icon pointing left">
  <h1>Get Growing</h1>
  <img src="{% static 'images/wheelbarrow.png' %}" alt="A wheelbarrow icon pointing right">
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit</button>
</form>

{% endblock %}